-- v0.04: user-owned cloud data for the A-share analysis app.
-- Run this script in Supabase SQL Editor before enabling online mode.

create table if not exists public.user_watchlist (
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    code text not null,
    name text not null,
    exchange text not null,
    market_status text not null default '正常',
    added_at timestamptz not null default now(),
    primary key (user_id, symbol)
);

create table if not exists public.recent_queries (
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    code text not null,
    name text not null,
    exchange text not null,
    market_status text not null default '正常',
    as_of date,
    last_queried_at timestamptz not null default now(),
    primary key (user_id, symbol)
);

create table if not exists public.analysis_snapshots (
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    price double precision,
    score double precision,
    as_of date,
    updated_at timestamptz not null default now(),
    primary key (user_id, symbol)
);

create table if not exists public.paper_accounts (
    user_id uuid primary key references auth.users(id) on delete cascade,
    cash double precision not null default 1000000,
    created_at timestamptz not null default now()
);

create table if not exists public.paper_orders (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    side text not null check (side in ('买入', '卖出')),
    shares integer not null check (shares > 0 and mod(shares, 100) = 0),
    price double precision not null check (price > 0),
    fee double precision not null default 0 check (fee >= 0),
    traded_at date not null,
    status text not null default 'filled',
    message text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_paper_orders_user_date
    on public.paper_orders(user_id, traded_at, id);

create table if not exists public.trade_plans (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    direction text not null,
    setup text not null,
    horizon text not null,
    entry_price double precision not null check (entry_price > 0),
    stop_loss double precision not null check (stop_loss > 0),
    take_profit double precision not null check (take_profit > 0),
    total_capital double precision not null check (total_capital > 0),
    risk_pct double precision not null check (risk_pct > 0 and risk_pct <= 1),
    max_position_pct double precision not null check (max_position_pct > 0 and max_position_pct <= 1),
    planned_shares integer not null check (planned_shares >= 0 and mod(planned_shares, 100) = 0),
    planned_amount double precision not null check (planned_amount >= 0),
    risk_budget double precision not null check (risk_budget >= 0),
    estimated_max_loss double precision not null check (estimated_max_loss >= 0),
    risk_reward double precision,
    thesis text not null default '',
    invalidation text not null default '',
    status text not null default 'planned',
    created_at timestamptz not null default now()
);

create index if not exists idx_trade_plans_user_symbol
    on public.trade_plans(user_id, symbol, created_at desc);

create table if not exists public.trade_reviews (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    plan_id bigint references public.trade_plans(id) on delete set null,
    review_date date not null,
    outcome text not null,
    execution_adherence integer not null check (execution_adherence between 0 and 100),
    mistake_tags jsonb not null default '[]'::jsonb,
    notes text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_trade_reviews_user_symbol
    on public.trade_reviews(user_id, symbol, review_date desc);

create table if not exists public.user_alert_settings (
    user_id uuid primary key references auth.users(id) on delete cascade,
    enabled boolean not null default true,
    price_threshold double precision not null default 3.0 check (price_threshold > 0),
    score_threshold double precision not null default 5.0 check (score_threshold > 0),
    updated_at timestamptz not null default now()
);

create or replace function public.touch_recent_query()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.last_queried_at = now();
    return new;
end;
$$;

drop trigger if exists recent_queries_touch on public.recent_queries;
create trigger recent_queries_touch
before insert or update on public.recent_queries
for each row execute function public.touch_recent_query();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists analysis_snapshots_touch on public.analysis_snapshots;
create trigger analysis_snapshots_touch
before insert or update on public.analysis_snapshots
for each row execute function public.touch_updated_at();

drop trigger if exists user_alert_settings_touch on public.user_alert_settings;
create trigger user_alert_settings_touch
before insert or update on public.user_alert_settings
for each row execute function public.touch_updated_at();

create or replace function public.record_paper_order(
    p_symbol text,
    p_side text,
    p_shares integer,
    p_price double precision,
    p_fee double precision,
    p_traded_at date,
    p_status text,
    p_message text,
    p_cash_delta double precision
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    new_id bigint;
    current_cash double precision;
    next_cash double precision;
    expected_delta double precision;
begin
    if auth.uid() is null then
        raise exception 'not authenticated';
    end if;
    if p_side not in (U&'\4E70\5165', U&'\5356\51FA') then
        raise exception 'invalid order side';
    end if;
    if p_shares <= 0 or mod(p_shares, 100) <> 0 then
        raise exception 'shares must be a positive multiple of 100';
    end if;
    if p_price <= 0 or p_fee < 0 then
        raise exception 'invalid order price or fee';
    end if;
    if p_cash_delta is null then
        raise exception 'cash delta cannot be null';
    end if;
    expected_delta := case
        when p_side = U&'\4E70\5165' then -(p_price * p_shares + p_fee)
        else p_price * p_shares - p_fee
    end;
    if abs(p_cash_delta - expected_delta) > 0.0001 then
        raise exception 'cash delta does not match order';
    end if;
    select cash into current_cash
    from public.paper_accounts
    where user_id = auth.uid()
    for update;
    if current_cash is null then
        raise exception 'paper account not found';
    end if;
    if p_side = U&'\5356\51FA' then
        if (
            select coalesce(sum(case when side = U&'\4E70\5165' then shares else -shares end), 0)
            from public.paper_orders
            where user_id = auth.uid()
              and symbol = p_symbol
              and status = 'filled'
        ) < p_shares then
            raise exception 'insufficient position';
        end if;
    end if;
    next_cash := current_cash + p_cash_delta;
    if next_cash < 0 then
        raise exception 'cash cannot be negative';
    end if;
    update public.paper_accounts
    set cash = next_cash
    where user_id = auth.uid();
    insert into public.paper_orders(
        user_id, symbol, side, shares, price, fee, traded_at, status, message
    ) values (
        auth.uid(), p_symbol, p_side, p_shares, p_price, p_fee,
        p_traded_at, p_status, p_message
    ) returning id into new_id;
    return new_id;
end;
$$;

grant execute on function public.record_paper_order(
    text, text, integer, double precision, double precision, date, text, text, double precision
) to authenticated;

do $$
declare
    table_name text;
    policy_suffix text;
begin
    foreach table_name in array array[
        'user_watchlist', 'recent_queries', 'analysis_snapshots',
        'paper_accounts', 'paper_orders', 'trade_plans',
        'trade_reviews', 'user_alert_settings'
    ] loop
        execute format('alter table public.%I enable row level security', table_name);
        foreach policy_suffix in array array['_select', '_insert', '_update', '_delete'] loop
            execute format('drop policy if exists %I on public.%I', table_name || policy_suffix, table_name);
            execute format('drop policy if exists %I on public.%I', table_name || '_user' || policy_suffix, table_name);
        end loop;
        execute format(
            'create policy %I on public.%I for select to authenticated using (user_id = auth.uid())',
            table_name || '_select', table_name
        );
        execute format(
            'create policy %I on public.%I for insert to authenticated with check (user_id = auth.uid())',
            table_name || '_insert', table_name
        );
        execute format(
            'create policy %I on public.%I for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())',
            table_name || '_update', table_name
        );
        execute format(
            'create policy %I on public.%I for delete to authenticated using (user_id = auth.uid())',
            table_name || '_delete', table_name
        );
    end loop;
end;
$$;
